export const seedIngredients = [
  {
    id: "tomates",
    name: "Tomates anciennes",
    category: "Fruits & légumes",
    unit: "kg",
    zone: "Chambre froide A",
    supplier: "Maraîcher Vallon",
    alternativeSupplier: "Metro Primeurs",
    packSize: 5,
    packLabel: "cagette 5 kg",
    price: 3.45,
    previousPrice: 3.08,
    leadTime: 1,
    targetDays: 3.5,
    safetyDays: 0.8,
    shelfLife: 5,
    critical: true,
    theoretical: 18.2,
    lastCounted: "hier",
    variance: -2.7,
    parMin: 14,
    parMax: 28,
    wasteRate: 0.07,
  },
  {
    id: "burrata",
    name: "Burrata 125 g",
    category: "Crèmerie",
    unit: "piece",
    zone: "Frigo produits finis",
    supplier: "Laiterie des Alpes",
    alternativeSupplier: "Épicerie Centrale",
    packSize: 8,
    packLabel: "colis 8 pieces",
    price: 2.75,
    previousPrice: 2.75,
    leadTime: 2,
    targetDays: 4,
    safetyDays: 1.2,
    shelfLife: 9,
    critical: true,
    theoretical: 42,
    lastCounted: "ce matin",
    variance: -4,
    parMin: 32,
    parMax: 64,
    wasteRate: 0.03,
  },
  {
    id: "basilic",
    name: "Basilic frais",
    category: "Fruits & légumes",
    unit: "kg",
    zone: "Chambre froide A",
    supplier: "Maraîcher Vallon",
    alternativeSupplier: "Metro Primeurs",
    packSize: 0.5,
    packLabel: "botte 500 g",
    price: 18.5,
    previousPrice: 15.6,
    leadTime: 1,
    targetDays: 2.5,
    safetyDays: 0.6,
    shelfLife: 4,
    critical: false,
    theoretical: 1.8,
    lastCounted: "hier",
    variance: -0.4,
    parMin: 1.4,
    parMax: 3,
    wasteRate: 0.12,
  },
  {
    id: "entrecote",
    name: "Entrecôte maturée",
    category: "Viandes",
    unit: "kg",
    zone: "Chambre froide viande",
    supplier: "Boucherie Lenoir",
    alternativeSupplier: "Grossiste Halles",
    packSize: 4,
    packLabel: "sous-vide 4 kg",
    price: 29.8,
    previousPrice: 28.1,
    leadTime: 2,
    targetDays: 5,
    safetyDays: 1.4,
    shelfLife: 10,
    critical: true,
    theoretical: 15.4,
    lastCounted: "hier",
    variance: 1.6,
    parMin: 16,
    parMax: 34,
    wasteRate: 0.05,
  },
  {
    id: "saumon",
    name: "Saumon frais",
    category: "Poissons",
    unit: "kg",
    zone: "Chambre froide poisson",
    supplier: "Poissonnerie Aria",
    alternativeSupplier: "Criée Express",
    packSize: 3,
    packLabel: "caisse 3 kg",
    price: 19.4,
    previousPrice: 20.2,
    leadTime: 1,
    targetDays: 3,
    safetyDays: 0.9,
    shelfLife: 4,
    critical: true,
    theoretical: 11,
    lastCounted: "ce matin",
    variance: -1.8,
    parMin: 10,
    parMax: 20,
    wasteRate: 0.06,
  },
  {
    id: "creme",
    name: "Crème 35%",
    category: "Crèmerie",
    unit: "L",
    zone: "Frigo pâtisserie",
    supplier: "Laiterie des Alpes",
    alternativeSupplier: "Épicerie Centrale",
    packSize: 6,
    packLabel: "carton 6 L",
    price: 4.2,
    previousPrice: 3.92,
    leadTime: 2,
    targetDays: 5,
    safetyDays: 1,
    shelfLife: 7,
    critical: false,
    theoretical: 22,
    lastCounted: "il y a 2 j",
    variance: -3.5,
    parMin: 18,
    parMax: 36,
    wasteRate: 0.04,
  },
  {
    id: "oeufs",
    name: "Œufs plein air",
    category: "Crèmerie",
    unit: "piece",
    zone: "Réserve sèche",
    supplier: "Laiterie des Alpes",
    alternativeSupplier: "Épicerie Centrale",
    packSize: 30,
    packLabel: "plateau 30",
    price: 0.32,
    previousPrice: 0.29,
    leadTime: 2,
    targetDays: 7,
    safetyDays: 1.2,
    shelfLife: 18,
    critical: true,
    theoretical: 180,
    lastCounted: "il y a 2 j",
    variance: -12,
    parMin: 150,
    parMax: 270,
    wasteRate: 0.02,
  },
  {
    id: "farine",
    name: "Farine T65",
    category: "Épicerie",
    unit: "kg",
    zone: "Réserve sèche",
    supplier: "Épicerie Centrale",
    alternativeSupplier: "Moulin local",
    packSize: 25,
    packLabel: "sac 25 kg",
    price: 1.05,
    previousPrice: 1.02,
    leadTime: 3,
    targetDays: 14,
    safetyDays: 2,
    shelfLife: 90,
    critical: false,
    theoretical: 84,
    lastCounted: "semaine derniere",
    variance: 5,
    parMin: 50,
    parMax: 125,
    wasteRate: 0.01,
  },
  {
    id: "beurre",
    name: "Beurre doux",
    category: "Crèmerie",
    unit: "kg",
    zone: "Frigo pâtisserie",
    supplier: "Laiterie des Alpes",
    alternativeSupplier: "Épicerie Centrale",
    packSize: 5,
    packLabel: "bloc 5 kg",
    price: 8.4,
    previousPrice: 7.7,
    leadTime: 2,
    targetDays: 8,
    safetyDays: 1.5,
    shelfLife: 21,
    critical: false,
    theoretical: 26,
    lastCounted: "il y a 3 j",
    variance: 0.8,
    parMin: 18,
    parMax: 45,
    wasteRate: 0.02,
  },
  {
    id: "pommes",
    name: "Pommes de terre",
    category: "Fruits & légumes",
    unit: "kg",
    zone: "Réserve légumes",
    supplier: "Maraîcher Vallon",
    alternativeSupplier: "Metro Primeurs",
    packSize: 10,
    packLabel: "sac 10 kg",
    price: 1.22,
    previousPrice: 1.18,
    leadTime: 1,
    targetDays: 7,
    safetyDays: 1,
    shelfLife: 18,
    critical: true,
    theoretical: 58,
    lastCounted: "hier",
    variance: 7,
    parMin: 42,
    parMax: 95,
    wasteRate: 0.03,
  },
  {
    id: "salade",
    name: "Mesclun lavé",
    category: "Fruits & légumes",
    unit: "kg",
    zone: "Chambre froide A",
    supplier: "Maraîcher Vallon",
    alternativeSupplier: "Metro Primeurs",
    packSize: 2,
    packLabel: "caisse 2 kg",
    price: 7.2,
    previousPrice: 6.1,
    leadTime: 1,
    targetDays: 2.5,
    safetyDays: 0.5,
    shelfLife: 3,
    critical: false,
    theoretical: 7.5,
    lastCounted: "ce matin",
    variance: -1.2,
    parMin: 6,
    parMax: 14,
    wasteRate: 0.14,
  },
  {
    id: "huile",
    name: "Huile olive extra",
    category: "Épicerie",
    unit: "L",
    zone: "Réserve sèche",
    supplier: "Épicerie Centrale",
    alternativeSupplier: "Cave Comète",
    packSize: 5,
    packLabel: "bidon 5 L",
    price: 9.9,
    previousPrice: 9.35,
    leadTime: 3,
    targetDays: 18,
    safetyDays: 2,
    shelfLife: 120,
    critical: true,
    theoretical: 34,
    lastCounted: "semaine derniere",
    variance: -2,
    parMin: 22,
    parMax: 55,
    wasteRate: 0.01,
  },
];

export const seedBatches = [
  { id: "lot-tom-1", ingredientId: "tomates", lot: "TOM-622", qty: 6, receivedOffset: -3, expiryOffset: 1, dateType: "DLC", openedOffset: -1, secondaryExpiryOffset: 1 },
  { id: "lot-tom-2", ingredientId: "tomates", lot: "TOM-623", qty: 9.5, receivedOffset: -1, expiryOffset: 4, dateType: "DLC" },
  { id: "lot-bur-1", ingredientId: "burrata", lot: "BUR-611", qty: 18, receivedOffset: -6, expiryOffset: 2, dateType: "DLC", openedOffset: -1, secondaryExpiryOffset: 2 },
  { id: "lot-bur-2", ingredientId: "burrata", lot: "BUR-623", qty: 20, receivedOffset: -1, expiryOffset: 8, dateType: "DLC" },
  { id: "lot-bas-1", ingredientId: "basilic", lot: "BAS-620", qty: 0.6, receivedOffset: -3, expiryOffset: 0, dateType: "DLC", openedOffset: -2 },
  { id: "lot-bas-2", ingredientId: "basilic", lot: "BAS-623", qty: 0.8, receivedOffset: -1, expiryOffset: 3, dateType: "DLC" },
  { id: "lot-ent-1", ingredientId: "entrecote", lot: "ENT-615", qty: 7.8, receivedOffset: -8, expiryOffset: 2, dateType: "DLC", openedOffset: -1, secondaryExpiryOffset: 1 },
  { id: "lot-ent-2", ingredientId: "entrecote", lot: "ENT-621", qty: 9.2, receivedOffset: -2, expiryOffset: 8, dateType: "DLC" },
  { id: "lot-sau-1", ingredientId: "saumon", lot: "SAU-622", qty: 4.5, receivedOffset: -2, expiryOffset: 1, dateType: "DLC", openedOffset: -1, secondaryExpiryOffset: 0 },
  { id: "lot-sau-2", ingredientId: "saumon", lot: "SAU-623", qty: 4.7, receivedOffset: -1, expiryOffset: 3, dateType: "DLC" },
  { id: "lot-cre-1", ingredientId: "creme", lot: "CRE-614", qty: 5, receivedOffset: -9, expiryOffset: -1, dateType: "DLC", openedOffset: -4 },
  { id: "lot-cre-2", ingredientId: "creme", lot: "CRE-620", qty: 13.5, receivedOffset: -3, expiryOffset: 5, dateType: "DLC", openedOffset: -1 },
  { id: "lot-oeu-1", ingredientId: "oeufs", lot: "OEU-616", qty: 78, receivedOffset: -7, expiryOffset: 9, dateType: "DLC" },
  { id: "lot-oeu-2", ingredientId: "oeufs", lot: "OEU-623", qty: 90, receivedOffset: -1, expiryOffset: 17, dateType: "DLC" },
  { id: "lot-far-1", ingredientId: "farine", lot: "FAR-601", qty: 89, receivedOffset: -20, expiryOffset: 70, dateType: "DDM" },
  { id: "lot-beu-1", ingredientId: "beurre", lot: "BEU-608", qty: 11, receivedOffset: -15, expiryOffset: 6, dateType: "DLC", openedOffset: -2, secondaryExpiryOffset: 5 },
  { id: "lot-beu-2", ingredientId: "beurre", lot: "BEU-621", qty: 15.8, receivedOffset: -2, expiryOffset: 19, dateType: "DLC" },
  { id: "lot-pom-1", ingredientId: "pommes", lot: "PDT-617", qty: 36, receivedOffset: -6, expiryOffset: 8, dateType: "DDM" },
  { id: "lot-pom-2", ingredientId: "pommes", lot: "PDT-622", qty: 29, receivedOffset: -1, expiryOffset: 17, dateType: "DDM" },
  { id: "lot-sal-1", ingredientId: "salade", lot: "SAL-621", qty: 2.6, receivedOffset: -2, expiryOffset: 0, dateType: "DLC", openedOffset: -1 },
  { id: "lot-sal-2", ingredientId: "salade", lot: "SAL-623", qty: 3.9, receivedOffset: -1, expiryOffset: 2, dateType: "DLC" },
  { id: "lot-hui-1", ingredientId: "huile", lot: "HUI-521", qty: 32, receivedOffset: -31, expiryOffset: 92, dateType: "DDM" },
];

export const recipes = [
  {
    id: "burrata-tomates",
    name: "Burrata tomates",
    station: "Froid",
    price: 16.5,
    dailyBase: 22,
    trend: 0.18,
    popularity: 91,
    ingredients: [
      { id: "tomates", qty: 0.22 },
      { id: "burrata", qty: 1 },
      { id: "basilic", qty: 0.012 },
      { id: "huile", qty: 0.025 },
    ],
  },
  {
    id: "saumon",
    name: "Saumon snacké",
    station: "Chaud",
    price: 27,
    dailyBase: 17,
    trend: 0.05,
    popularity: 78,
    ingredients: [
      { id: "saumon", qty: 0.19 },
      { id: "pommes", qty: 0.22 },
      { id: "beurre", qty: 0.025 },
      { id: "salade", qty: 0.04 },
    ],
  },
  {
    id: "entrecote",
    name: "Entrecôte frites",
    station: "Grill",
    price: 31,
    dailyBase: 21,
    trend: 0.02,
    popularity: 86,
    ingredients: [
      { id: "entrecote", qty: 0.24 },
      { id: "pommes", qty: 0.3 },
      { id: "beurre", qty: 0.018 },
      { id: "salade", qty: 0.035 },
    ],
  },
  {
    id: "pates-pesto",
    name: "Pâtes fraîches pesto",
    station: "Chaud",
    price: 19,
    dailyBase: 19,
    trend: 0.12,
    popularity: 81,
    ingredients: [
      { id: "farine", qty: 0.12 },
      { id: "oeufs", qty: 1.1 },
      { id: "basilic", qty: 0.035 },
      { id: "huile", qty: 0.028 },
    ],
  },
  {
    id: "tarte-citron",
    name: "Tarte citron",
    station: "Pâtisserie",
    price: 9,
    dailyBase: 28,
    trend: -0.02,
    popularity: 74,
    ingredients: [
      { id: "farine", qty: 0.055 },
      { id: "beurre", qty: 0.04 },
      { id: "oeufs", qty: 0.8 },
      { id: "creme", qty: 0.045 },
    ],
  },
  {
    id: "salade-maison",
    name: "Salade de saison",
    station: "Froid",
    price: 14,
    dailyBase: 16,
    trend: 0.08,
    popularity: 70,
    ingredients: [
      { id: "salade", qty: 0.09 },
      { id: "tomates", qty: 0.12 },
      { id: "basilic", qty: 0.008 },
      { id: "huile", qty: 0.018 },
    ],
  },
];

export const suppliers = [
  { name: "Maraîcher Vallon", cutoff: "10:30", delivery: "lun-sam", reliability: 94, minOrder: 80, phone: "+41791112233", email: "commandes@maraicher-vallon.ch" },
  { name: "Laiterie des Alpes", cutoff: "15:00", delivery: "mar-jeu-sam", reliability: 91, minOrder: 60, phone: "+41792223344", email: "ventes@laiterie-alpes.ch" },
  { name: "Boucherie Lenoir", cutoff: "12:00", delivery: "lun-mer-ven", reliability: 89, minOrder: 120, phone: "+41793334455", email: "commande@boucherie-lenoir.ch" },
  { name: "Poissonnerie Aria", cutoff: "09:00", delivery: "tous les matins", reliability: 96, minOrder: 100, phone: "+41794445566", email: "pro@poissonnerie-aria.ch" },
  { name: "Épicerie Centrale", cutoff: "16:00", delivery: "48 h", reliability: 88, minOrder: 150, phone: "+41795556677", email: "b2b@epicerie-centrale.ch" },
  { name: "Cave Comète", cutoff: "14:00", delivery: "72 h", reliability: 92, minOrder: 200, phone: "+41796667788", email: "cave@comete-vins.ch" },
];

export const seedLogs = [
  { id: "log-1", type: "Réception", item: "Saumon frais", qty: "4.7 kg", user: "Mina", time: "08:14", note: "Lot SAU-623, livraison conforme" },
  { id: "log-2", type: "Perte", item: "Mesclun lavé", qty: "0.8 kg", user: "Rayan", time: "09:05", note: "Feuilles fatiguées avant service" },
  { id: "log-3", type: "Inventaire", item: "Burrata 125 g", qty: "-4 pieces", user: "Mina", time: "10:22", note: "Écart vs théorie" },
  { id: "log-4", type: "Prix", item: "Basilic frais", qty: "+18.6%", user: "Système", time: "10:24", note: "Comparer fournisseur alternatif" },
];

export const defaultScenario = {
  demandIndex: 108,
  eventCovers: 26,
  supplierDelay: 0,
  safetyBuffer: 0.4,
  wasteDiscipline: 72,
};

export const controlChecks = [
  {
    id: "trace-reception",
    label: "Réceptions avec lot + DLC/DDM",
    area: "Traçabilité",
    cadence: "à chaque livraison",
    due: "avant rangement",
    status: "attention",
    owner: "Chef de partie",
    evidence: "1 lot crème à isoler",
  },
  {
    id: "secondary-labels",
    label: "Étiquettes secondaires produits ouverts",
    area: "Autocontrôle",
    cadence: "quotidien",
    due: "11:00",
    status: "todo",
    owner: "Mina",
    evidence: "crème ouverte à relabeliser",
  },
  {
    id: "waste-review",
    label: "Pertes par motif",
    area: "Marge",
    cadence: "fin de service",
    due: "23:00",
    status: "todo",
    owner: "Responsable soir",
    evidence: "mesclun et basilic à expliquer",
  },
];

export const swissRules = {
  country: "Suisse",
  currency: "CHF",
  traceability: "Conserver les éléments permettant de retrouver fournisseur, lot, date de réception et destination interne.",
  dateTypes: {
    DLC: "Sécurité: ne pas utiliser après dépassement.",
    DDM: "Qualité: contrôler produit et conditions avant décision.",
  },
};
